dependencies:
  # rimappaggio per gli import su contatto
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'
# creo i dati per deployare il mio contratto
dotenv: .env
networks:
  default: development
  development:
    initialSupply: 21000000000000000000000000
  rinkeby:
    initialSupply: 21000000000000000000000000
    verify: true
wallets:
  from_key: ${PRIVATE_KEY}